site_name: Arkane Linux
site_url: https://docs.arkanelinux.org/
site_description: "An opinionated, immutable, atomic, multi-root Arch-based distibution."
copyright: "CC BY-SA 4.0 Arkane Linux"

theme:
  name: mkdocs
  custom_dir: theme_overrides/

nav:
  - About: index.md
  - Technical Overview: arkanelinux.md
  - Arkdep:
    - 'arkdep usage': arkdep/arkdep.md
    - 'arkdep-build usage': arkdep/arkdep-build.md
    - 'arkdep repository': arkdep/arkdep-repository.md
  - Patch Notes:
    - 'arkdep': patch_notes/arkdep.md
    - 'os-installer-arkdep': patch_notes/osi-arkdep.md
