site_name: Arkane Linux
site_url: https://docs.arkanelinux.org/
site_description: "An opinionated, immutable, atomic, multi-root Arch-based distibution."
copyright: "CC-BY-SA-4.0 Arkane Linux"

nav:
  - Introduction: arkanelinux.md
  - Arkdep:
    - 'arkdep usage': arkdep.md
    - 'arkdep-build usage': arkdep-build.md

extra_css:
  - style.css
