site_name: Arkane Linux
site_url: https://docs.arkanelinux.org/
site_description: "An opinionated, immutable, atomic, multi-root Arch-based distibution."
copyright: "CC BY-SA 4.0 Arkane Linux"

theme:
  name: mkdocs
  custom_dir: theme_overrides/

nav:
  - About: index.md
  - Technical Overview: arkanelinux.md
  - Arkdep:
    - 'How it works': arkdep/arkdep-explained.md
    - 'Arkdep usage': arkdep/arkdep.md
    - 'Arkdep-build usage': arkdep/arkdep-build.md
    - 'Arkdep repository': arkdep/arkdep-repository.md
    - 'Arkdep migrations': arkdep/arkdep-migrations.md
    - 'Set up Arkdep on a new system': arkdep/arkdep-init.md
    - 'How do I...': arkdep/how-do-i.md
  - Patch Notes:
    - 'arkdep': patch_notes/arkdep.md
    - 'os-installer-arkdep': patch_notes/osi-arkdep.md
    - 'Arkane Linux': patch_notes/arkane.md
